INSERT INTO episode (season_id, title, number, synopsis) VALUES
(3, "Graines", 1, "
Après la nuit traumatisante au cours de laquelle ils ont dû abandonner la ferme de Hershel, Rick et les autres survivants cherchent un nouvel abri. Cela devient d'autant plus urgent qu'ils ont passé plusieurs mois dehors à la merci des rôdeurs, que tous sont épuisés et que l'accouchement de Lori est imminent. Après avoir fouillé toutes les maisons des alentours, ils arrivent à un endroit qu'ils n'avaient pas encore visité. Mais celui-ci est investi par les morts-vivants et risque d'être difficile à s'approprier. Rick, dont les décisions ne sont plus discutées, choisit cependant de saisir cette chance et entâme la sécurisation des lieux..."),
(3, "Malade", 2, "
L'opération pour éliminer les rôdeurs de la prison et accéder au stock d'armes et de médicaments a pris une tournure dramatique pour Hershel qui s'est fait mordre par un mort-vivant. Il est entre la vie et la mort après que Rick l'ai amputé d'une jambe pour tenter de le sauver. D'autre part, les survivants réalisent qu'ils ne sont pas les seuls à occuper la prison. Ils doivent trouver un arrangement pour co-habiter avec les détenus qui y vivent. Mais peuvent-ils leur faire confiance ? Ces derniers, qui étaient restés reclus près du garde-manger, n'avaient pas mesuré l'ampleur de la situation a l'extérieur..."),
(3, "Marchez avec moi", 3, "Andrea et Michonne sont témoin d'un accident d'hélicoptère. Méfiantes, elles se cachent pour assister à la scène. Alors que les survivants sont pris en charge par des hommes armés, elles se font repérer et sont emmenées dans un endroit protégé des zombies appelé Woodbury. Dirigé par un homme énigmatique qui se fait appeler le gourverneur, elles y trouvent des soins médicaux, de quoi reprendre des forces et Andrea découvre que Merle Dixon, le frère de Daryl, est encore en vie. Mais si cette dernière semble apprécier le lieu, Michonne se méfie de ses apparences trop idylliques..."),
(3, "Un tueur à l'intérieur", 4, "
A Woodburry, le gouverneur tente en vain d'obtenir la confiance de Michonne. Celle-ci est bien décidée à lever le camp dès que possible. Andrea, elle, n'est pas pressée de s'en aller et donne à Merle toutes les informations dont elle dispose sur son frère. Pendant ce temps, à la prison, les efforts du groupe pour rendre l'endroit vivable commencent à porter leurs fruits. Hershel, désormais rétabli, fait ses premiers pas aidé de béquilles et s'imagine vivre paisiblement dans cet endroit. Mais ce bonheur est de courte durée puisqu'une nouvelle fois, les rôdeurs mettent la vie des survivants en danger..."),
(3, "Le Dis-le", 5, "
Rick est inconsolable après la décès de Lori et ce sont les autres survivants qui prennent en charge le nouveau-né. Tandis que Maggie et Daryl partent à la recherche de nourriture et de matériel de puériculture, Glenn lui, entreprend d'enterrer les corps. A Woodburry, Michonne, qui veut récupérer son arme, fouille dans les affaires du gouverneur et découvre certains de ses secrets. Cela renforce sa volonté de partir rapidement et engendre une nouvelle dispute avec Andrea qui, elle, sent de plus en plus à sa place dans cette communauté. Alors que la première part seule, la seconde assiste à un spectacle pour le moins particulier..."),
(3, "La traque", 6, "
A nouveau en errance dans la forêt après avoir quitté Woodburry, Michonne n'est plus menacée uniquement par les morts-vivants, elle doit aussi se cacher des hommes de main du gouverneur qui sont à ses trousses. Andrea, au contraire, s'investit de plus en plus dans la vie du village et se rapproche du gouverneur. Dans le même temps, à la prison, Rick s'isole du groupe et ne parvient pas à se remettre de la mort de Lori. Phénomène étrange : il reçoit un coup de téléphone. Glenn et Maggie, sont, eux, partis chercher des vivres mais font une mauvaise rencontre..."),
(3, "Quand les morts approchent", 7, "
Maggie et Glenn ont été capturés par le gouverneur qui tente de leur soutirer des informations sur leur lieu de vie. Michonne a, elle, trouvé la prison et fait la connaissance de Rick. Elle lui apprend l'existence de Woodburry et que ses amis y sont retenus. Avec l'aide de Daryl, Oscar et de cette nouvelle combattante, ils tentent de leur venir en aide..."),
(3, "Une vie de souffrance", 8, "
Rick et les autres sont partis en mission pour tenter de libérer Maggie et Glenn. Malgré le peu de confiance qu'ils accordent à Michonne, ils parviennent à entrer dans la ville fortifiée. Tandis que Michonne découvre les sombres secrets du gouverneur, Andréa se bat sans le savoir contre ses anciens amis et Daryl apprend que son frère vit à Woodburry. Pendant ce temps, à la prison, Carl fait la connaissance de nouveaux survivants..."),
(3, "Le roi du suicide", 9, "Daryl et Merle, qui se sont retrouvés lors d'un duel à mort imposé par le gouverneur, parviennent à s'échapper tout deux vivants de Woodburry. Mais face à la personnalité de son frère et à la violence dont celui-ci a fait preuve envers Glenn et Maggie, Daryl préfère quitter le groupe et partir de son côté avec Merle. De retour à la prison, Rick, plus méfiant que jamais et toujours en proie à des visions, congédie Tyreese et les siens qui comptaient s'installer dans une partie du bâtiment. Dans le même temps, Andrea tente de contenir la panique qui s'empare des habitants de Woodburry..."),
(3, "Chez nous", 10, "Rick ne cesse d'aperçevoir Lori et le groupe s'inquiète de ses réactions parfois incontrôlées. Tous tentent de trouver une solution pour parer aux représailles du gouverneur. Alors que certains pensent survivre en fuyant la prison, d'autres ne peuvent se résoudre à quitter ces lieux qu'ils ont mis tant de temps et d'énergie à s'approprier. Mais le gouverneur dispose de bien plus d'armes et d'hommes qu'ils n'en auront jamais. Pendant ce temps, à Woodburry, ce dernier assure à Andrea ne pas vouloir se venger. Il lui confie son envie de céder son rôle de leader. Mais joue-t-il franc jeu ? A la prison, le groupe de Rick, va vite le savoir..."),
(3, "Entre deux feux", 11, "
La guerre est officiellement déclarée depuis que le gouverneur a attaqué la prison à l'aide d'une fourgonnette remplie de rôdeurs. Le leader de Woodburry fait le bilan de ses ressources disponibles en hommes et en armes, sollicitant l'aide de tous les habitants afin de lever une armée. Andrea, qui veut à tout prix éviter un bain de sang, se rend à la prison pour discuter avec ses anciens amis. Là-bas, le retour de Daryl et de Merle suscite la crainte mais permet d'avoir des informations sur l'ennemi. Alors que deux solutions semblent s'offrir au groupe de Rick : fuir ou attaquer, Carol propose à Andrea un plan alternatif..."),
(3, "Retrouvailles", 12, "Le groupe décide finalement de rester à la prison et de se préparer à une nouvelle attaque du gouverneur. Rick, qui dispose des clés du local de son ancien commissariat de police, se propose de chercher des armes et des munitions. En compagnie de Michonne et de Carl, il se rend dans son ancienne ville, là où tout a commencé, et fait la rencontre d'une vieille connaissance. Carl, qui a bien grandit et porte désormais sa propre arme, décide de partir seul en mission. Mais l'aide de Michonne va finalement s'avérer utile et permet à cette dernière d'enfin gagner la confiance du jeune garçon..."),
(3, "Une flèche sur la porte", 13, "
Les leaders de la prison et de Woodburry se rencontrent pour tenter de trouver un accord de paix. Chacun vient avec sa proposition mais celle de Rick, de partager le territoire en deux, de sorte à ne jamais se recroiser, ne satisfait pas le gouverneur. Celui-ci, toujours dans un esprit de vengeance, lui propose un tout autre marché et promet en échange d'épargner la prison et ses habitants. Là-bas, Maggie et Glenn peinent à calmer Merle qui s'est mis en tête d'écourter l'entrevue de Rick en abattant purement et simplement le gouverneur. Déterminé, il tente de rallier Michonne à sa cause..."),
(3, "PLa proie", 14, "
Alors qu'à Woodburry, Andrea et Milton ouvrent les yeux sur la personnalité de leur leader, à la prison, Rick reconsidère l'offre de livrer Michonne au gouverneur..."),
(3, "Cette triste vie", 15, "Rick et son groupe doivent faire face à un problème a priori insoluble. Les circonstances exigent pourtant une décision rapide. En effet, la nécessité d'une trêve avec le gouverneur se faisant de plus en plus pressante, les survivants vont devoir se résoudre à des sacrifices exorbitants. Michonne, surtout, est en danger : Rick demande à Merle de kidnapper la jeune femme et de l'envoyer chez le gouverneur. Sur le chemin, tous deux tombent dans une embuscade..."),
(3, "Bienvenue dans le tombeau", 16, "Après avoir demandé qu'on lui livre Michonne comme condition à la paix entre les groupes, le gouverneur franchit une nouvelle étape. Mais la mort de Merle accroît la tension. Andrea est toujours retenue prisonnière à Woodburry. Elle ne peut empêcher le gouverneur de prendre la décision d'attaquer la prison. Rick et les siens vont devoir se battre face à des hommes lourdement armés et vont devoir improviser pour s'en sortir vivants...")
;
