INSERT INTO episode (season_id, title, number, synopsis) VALUES
(2, "Ce qui nous attend", 1, "
Les survivants se retrouvent bloqués sur une route envahie par des carcasses de voitures. Ils décident d'en profiter pour siphonner les réservoirs. C'est alors qu'ils sont surpris par un groupe de zombies. Dale tente de superviser les opérations du haut du camion, tandis que Sophia, imprudente, est poursuivie par un groupe de zombies tenaces. Rick parvient à tuer les créatures qui menaçaient Sophia mais la jeune fille disparaît. Rick et les autres se lancent à sa poursuite..."),
(2, "Saignée", 2, "
Otis, le chasseur, a indiqué à Rick que les habitants de la ferme pourraient sauver Carl, blessé par balles. Le policier, qui porte son fils inconscient, tente désespérément de rejoindre la ferme. Le docteur Hershel Greene, propriétaire de l'endroit, pense pouvoir sauver le garçon en pratiquant une transfusion sanguine. Rick, qui possède le même groupe sanguin que son fils, donne son sang. Mais le médecin a besoin de matériel médical pour pouvoir opérer correctement. Otis et Shane se portent volontaires pour aller en chercher dans le lycée voisin. Pendant ce temps, Andrea est attaquée par un zombie. Elle est sauvée in extremis par Maggie, la fille de Hershel..."),
(2, "Le tout pour le tout", 3, "
L'angoisse règne toujours à la ferme. Le petit Carl est entre la vie et la mort. Les familles Greene et Grimes attendent des nouvelles de Shane et Otis, partis chercher du matériel médical au lycée. Mais ce qu'ils ne savent pas, c'est que Shane et Otis sont désormais prisonniers du lycée, qui est peu à peu envahi par une horde de zombies. De leur côté, Daryl et Andrea continuent à rechercher Sophia."),
(2, "Rose Cherokee", 4, "
Tous les survivants se retrouvent à la ferme des Greene. Maggie et Glenn, profitant d'une escapade au bourg voisin, se laissent aller à leur attirance mutuelle. Shane, depuis la mort d'Otis, a du mal à dissimuler sa part sombre. Pendant ce temps, Daryl continue de chercher la jeune Sophia disparue..."),
(2, "Le Chupacabra", 5, "
Dans les bois aux alentours de la ferme de la famille Greene, Daryl s'aventure à la recherche d'indices sur la disparition de Sophia. Malencontreusement, il se blesse assez gravement. Pour ne rien arranger, il doit faire face à des zombies et malgré ses talents de chasseur, sa situation devient critique. Pendant ce temps, Rick devine qu'il est en train de se passer quelque chose de grave. A la ferme d'Herschel Greene, les relations entre Glenn et Maggie deviennent plus évidentes. Glenn a une appréciation positive sur l'attitude de Maggie mais doute encore des sentiments naissants entre eux..."),
(2, "Secrets", 6, "
Pour les survivants emmenés par Rick Grimes, les temps deviennent difficiles : alors que l'humanité des uns et des autres est mise à rude épreuve et que le danger est omniprésent à cause des zombies, les relations entre humains sont constamment sur la corde raide. Le jeune Glenn devient ainsi le dépositaire de deux lourds secrets. Va-t-il en supporter le poids ? De son côté, Rick doit révéler un élément de la vie d'une personne proche de lui. Qu'en sera-t-il des conséquences ? Andrea, quant à elle, développe de nouvelles aptitudes et doit s'en servir lors d'un affrontement sans merci..."),
(2, "Déjà plus ou moins mort", 7, "
Entre les survivants, emmenés par Rick, et les habitants de la ferme Greene, les discussions sont vives sur l'attitude à adopter face au monde et ce qu'il est devenu. Hershel refuse de voir une certaine réalité. Andrea, de son côté, affirme sa personnalité et sort peu à peu de sa coquille. Entre les secrets des uns et des autres, l'ambiance devient pesante. Mais tous prennent de plus en plus conscience que dans ce monde devenu un enfer permanent, tout un chacun est considéré comme de la nourriture pour les autres..."),
(2, "Nebraska", 8, "
Les morts vivants retenus dans la grange ont tous été tués. La tension monte d'un cran au sein du petit groupe de survivants. Hershel Greene veut que Rick et ses amis quittent immédiatement sa ferme. Shane s'en prend à Rick et l'accuse de ne pas être assez réaliste sur la situation, sachant que Sophia se trouvait dans la grange. Dale prévient Andrea et Lori de se méfier de Shane et de sa personnalité trouble, d'autant plus qu'il le soupçonne de ne pas avoir dit toute la vérité sur la mort d'Otis..."),
(2, "Le Doigt sur la détente", 9, "
Pour les survivants, la situation ne s'améliore pas. Après les multiples dissensions qui ont fait exploser le groupe, où l'attitude de Shane a été un élément déterminant, chacun tente de suivre sa propre voie. Rick et Glenn ont suivi Hershel lorsqu'il est parti en ville alors qu'il s'était fait une règle de ne jamais quitter sa ferme. Malencontreusement, les trois hommes se retrouvent pris au piège et doivent se battre contre des morts-vivants. De son côté, Shane découvre que Lori est en danger..."),
(2, "A dix-huit miles, au moins", 10, "
Rick, accompagné de Shane, emmène Randall au plus loin de la ferme des Greene pour le perdre afin qu'il n'en retrouve pas le chemin. Ils l'abandonnent dans une ancienne école et se disputent quant à son sort. Shane veut l'exécuter alors que Rick demande une nuit pour réfléchir à cette question. Mais les trois hommes sont attaqués par des rôdeurs. A la ferme, Beth, désespérée de vivre dans un monde aussi violent, veut mettre fin à ses jours. Lori et Andrea n'ont pas la même opinion sur l'attitude à adopter vis-à-vis d'elle. Quant à Maggie, elle cherche surtout à protéger sa soeur..."),
(2, "Juge, Juré et Bourreau", 11, "
Alors que l'hiver approche et que les survivants tentent de s'organiser pour rester loin des ennuis et des morts-vivants qui rôdent aux alentours, l'ambiance dans le groupe est toujours aussi pesante. Rick et Shane ne s'entendent pas sur l'attitude à adopter vis-à-vis de Randall. A la ferme, Dale s'interroge sur la part d'humanité qui subsiste encore dans le groupe. Les actions du jeune Carl portent à conséquences. Quant à Beth, Andrea et Lori continuent de la surveiller après sa tentative de suicide..."),
(2, "Les Meilleurs Anges de notre nature", 12, "
Dale a été attaqué par un rôdeur aux alentours de la ferme et il n'a pas survécu à ses blessures. Tout le monde dans le groupe est choqué par sa disparition, car il représentait une part d'humanité dans ce monde violent. Rick, Shane et les autres doivent maintenant redoubler d'attention car les rôdeurs peuvent frapper à n'importe quel moment. Leur priorité reste la sécurité du groupe. De plus, Randall pose problème. Rick voulait le tuer mais il n'a pas pu l'exécuter sous les yeux de son fils. Le jeune homme est-il fiable ?..."),
(2, "Près du feu mourant", 13, "
De retour des bois qui entourent la ferme, Rick et son fils Carl découvrent que l'endroit où ils vivent depuis plusieurs semaines est devenu un véritable chaos. Le petit groupe de survivants est complètement séparé et les derniers semblants d'unité ont volé en éclats. La ferme des Greene n'est plus le havre de paix espéré par certains. De plus, le leadership de Rick sur le groupe est désormais remis en cause..."),
(2, "Près du feu mourant", 14, "
De retour des bois qui entourent la ferme, Rick et son fils Carl découvrent que l'endroit où ils vivent depuis plusieurs semaines est devenu un véritable chaos. Le petit groupe de survivants est complètement séparé et les derniers semblants d'unité ont volé en éclats. La ferme des Greene n'est plus le havre de paix espéré par certains. De plus, le leadership de Rick sur le groupe est désormais remis en cause..."),
(2, "Près du feu mourant", 15, "
De retour des bois qui entourent la ferme, Rick et son fils Carl découvrent que l'endroit où ils vivent depuis plusieurs semaines est devenu un véritable chaos. Le petit groupe de survivants est complètement séparé et les derniers semblants d'unité ont volé en éclats. La ferme des Greene n'est plus le havre de paix espéré par certains. De plus, le leadership de Rick sur le groupe est désormais remis en cause..."),
(2, "Près du feu mourant", 16, "
De retour des bois qui entourent la ferme, Rick et son fils Carl découvrent que l'endroit où ils vivent depuis plusieurs semaines est devenu un véritable chaos. Le petit groupe de survivants est complètement séparé et les derniers semblants d'unité ont volé en éclats. La ferme des Greene n'est plus le havre de paix espéré par certains. De plus, le leadership de Rick sur le groupe est désormais remis en cause...")
;
