<?php

namespace ContainerIugxKZg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7WX2RVOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7WX2RVO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7WX2RVO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actorRepository' => ['privates', 'App\\Repository\\ActorRepository', 'getActorRepositoryService', true],
        ], [
            'actorRepository' => 'App\\Repository\\ActorRepository',
        ]);
    }
}
