<?php

namespace ContainerIugxKZg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SDvoBPQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SDvoBPQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SDvoBPQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'episode' => ['privates', '.errored..service_locator.SDvoBPQ.App\\Entity\\Episode', NULL, 'Cannot autowire service ".service_locator.SDvoBPQ": it references class "App\\Entity\\Episode" but no such service exists.'],
        ], [
            'episode' => 'App\\Entity\\Episode',
        ]);
    }
}
