<?php

namespace ContainerIugxKZg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CF0apD9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cF0apD9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cF0apD9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actor' => ['privates', '.errored..service_locator.cF0apD9.App\\Entity\\Actor', NULL, 'Cannot autowire service ".service_locator.cF0apD9": it references class "App\\Entity\\Actor" but no such service exists.'],
        ], [
            'actor' => 'App\\Entity\\Actor',
        ]);
    }
}
