<?php

namespace ContainerIugxKZg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEpisode2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SDvoBPQ.App\Entity\Episode' shared service.
     *
     * @return \App\Entity\Episode
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SDvoBPQ": it references class "App\\Entity\\Episode" but no such service exists.');
    }
}
