<?php

namespace ContainerOUHWAXX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AP4yyEHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aP4yyEH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aP4yyEH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'seasonRepository' => ['privates', 'App\\Repository\\SeasonRepository', 'getSeasonRepositoryService', true],
        ], [
            'seasonRepository' => 'App\\Repository\\SeasonRepository',
        ]);
    }
}
