<?php

namespace ContainerOUHWAXX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgramService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..9nEn1O.App\Entity\Program' shared service.
     *
     * @return \App\Entity\Program
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..9nEn1O": it references class "App\\Entity\\Program" but no such service exists.');
    }
}
