<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIugxKZg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIugxKZg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIugxKZg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIugxKZg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIugxKZg\App_KernelDevDebugContainer([
    'container.build_hash' => 'IugxKZg',
    'container.build_id' => 'b71937fa',
    'container.build_time' => 1615557282,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIugxKZg');
